---
title: "**Tráfico Minnesota**"
author:
- Federico Alfaro Chaverri B80212
- María José Bolaños Gutierrez C01218
- Albert Gutiérrez Castro B93612
- Sofía Sequeira Ugalde B97458
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: spacelab
    highlight: zenburn
toc-title: "Tabla de Contenido"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(tidyr)
```

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggplot2)
library(fpp3)
library(astsa)
library(timetk)
```

```{r}
trafico <- read.csv("Metro_Interstate_Traffic_Volume.csv",
                              stringsAsFactors = TRUE, 
                              colClasses = c("factor",
                                             "numeric",  # temp (double o large)
                                             "numeric",  # rain_1h (double o large)
                                             "numeric",  # snow_1h (double o large)
                                             "integer",  # clouds_all (int)
                                             "factor",   # weather_main
                                             "factor",   # weather_description
                                             "character",     # date_time (y-m-d)
                                             "character" # traffic_volume (hora puede ser tratado como texto en caso de no ser numérico)
                                             ))
trafico
```

```{r}
trafico[1,]
```

```{r}
trafico[dim(trafico)[1],]
```

```{r}
# Usar separate para dividir la columna
#trafico <- trafico %>%
#  separate(date_time, into = c("day", "time"), sep = " ")

#trafico
```



```{r}

trafico <- trafico[-which(duplicated(trafico$date_time)), ]

```




```{r}
trafico
```

```{r}
date_time <- as.POSIXct(trafico$date_time, format = "%Y-%m-%d %H:%M:%S", tz = "America/Chicago")

# Definir la fecha de inicio y fin en la misma zona horaria
fecha_inicio <- as.POSIXct("2012-10-02 09:00:00", format = "%Y-%m-%d %H:%M:%S", tz = "America/Chicago")
fecha_fin <- as.POSIXct("2018-09-30 23:00:00", format = "%Y-%m-%d %H:%M:%S", tz = "America/Chicago")

# Crear una secuencia completa de horas entre la fecha de inicio y fin
horas_completas <- seq.POSIXt(from = fecha_inicio, to = fecha_fin, by = "hour")

# Encontrar las horas que faltan
horas_faltantes <- setdiff(horas_completas, date_time)

# Convertir horas_faltantes a un formato legible
horas_faltantes_legibles <- as.POSIXct(horas_faltantes, origin = "1970-01-01", tz = "America/Chicago")

# Mostrar las horas faltantes, si las hay
if (length(horas_faltantes_legibles) > 0) {
  # Imprimir las horas faltantes en formato POSIXct
  print(horas_faltantes_legibles)  # Esto mostrará la fecha y la hora completa
} else {
  print("No hay horas faltantes")
}
```

```{r}
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "01:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "02:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "03:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "04:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "05:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "06:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "07:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "08:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "09:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "10:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "11:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "12:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "13:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "14:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "15:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "16:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "17:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "18:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "19:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "20:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "21:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "22:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "23:00:00"])
length(horas_faltantes_legibles[format(horas_faltantes_legibles, "%H:%M:%S") == "00:00:00"])
```



